name: Run K6 and Artillery tests

on: [push]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js (Upgrade to v18)
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install k6 (via Snap)
        run: sudo snap install k6

      - name: Run K6 tests
        run: npm run test:k6

      - name: Run Artillery tests
        run: npm run test:artillery
